server:
  port: 9091
  tomcat:
    remoteip:
      remote-ip-header: x-forwared-for
      protocol-header: x-forwared-proto
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false